- Tweak: use tar's -S option to handle sparse files efficiently. - Cosmetic: Adjust indention.

diff --git a/ballup b/ballup
--- a/ballup
+++ b/ballup
@@ -3,20 +3,19 @@
 
 cancel_op() {
 
- echo "Operation canceled, exiting..."
+    echo "Operation canceled, exiting..."
  
- if [ -d "$destination" ] && [ -f "$destination/$filename" ]; then
+    if [ -d "$destination" ] && [ -f "$destination/$filename" ]; then
  
-    local interval=$(( $(date +%s) - $(stat -c "%Y" "$destination/$filename") ))
+        local interval=$(( $(date +%s) - $(stat -c "%Y" "$destination/$filename") ))
     
-    if [ $interval -lt 86400 ]; then
-       rm "$destination/$filename"
-    fi
+        if [ $interval -lt 86400 ]; then
+            rm "$destination/$filename"
+        fi
        
- fi
+    fi
  
- exit 1
-
+    exit 1
 }
 
 trap cancel_op SIGINT SIGTERM
@@ -28,27 +27,27 @@ backup() {
    
     case $compression in
             
-             gzip) local multi_thr_algo="pigz"; std_algo="gzip";;   
-                    
-             bzip) local multi_thr_algo="pbzip2"; std_algo="bzip2";;
-                       
-             xz) local multi_thr_algo="pixz"; std_algo="xz";;
+        gzip) local multi_thr_algo="pigz"; std_algo="gzip";;   
+            
+        bzip) local multi_thr_algo="pbzip2"; std_algo="bzip2";;
+               
+        xz) local multi_thr_algo="pixz"; std_algo="xz";;
 
-             zst) local multi_thr_algo="zstdmt"; std_algo="zstd";;
-                       
-             *) echo "Unrecognized compression algorithm, aborting..."; exit -1;;
+        zst) local multi_thr_algo="zstdmt"; std_algo="zstd";;
+               
+        *) echo "Unrecognized compression algorithm, aborting..."; exit -1;;
             
     esac   
     
     if which "$multi_thr_algo" > /dev/null; then
-       local comp_param="-I $multi_thr_algo"
-       echo "Using multithreaded $compression implementation"
+        local comp_param="-I $multi_thr_algo"
+        echo "Using multithreaded $compression implementation"
     elif which "$std_algo" > /dev/null; then
-       local comp_param="--$std_algo"
-       echo "Using standard $compression implementation"
+        local comp_param="--$std_algo"
+        echo "Using standard $compression implementation"
     else
-       echo "No implementation of the requested compression algorithm found on this machine! Exiting..."
-       exit -1
+        echo "No implementation of the requested compression algorithm found on this machine! Exiting..."
+        exit -1
     fi   
     
     sleep 3
@@ -56,32 +55,32 @@ backup() {
     
     if [ "$choice" = "full" ]; then
     
-      tar "$comp_param" \
-          $(if [ -n "$verbose" ]; then echo "-v"; else echo "--totals"; fi) \
-          -cpf "$destination/$filename" \
-          --exclude="$destination/$filename" \
-	  $(for entry in "${std_exclude_dirs[@]}"; do echo -n "--exclude=$entry "; done) /
+        tar "$comp_param" \
+            $(if [ -n "$verbose" ]; then echo "-v"; else echo "--totals"; fi) \
+            -Scpf "$destination/$filename" \
+            --exclude="$destination/$filename" \
+            $(for entry in "${std_exclude_dirs[@]}"; do echo -n "--exclude=$entry "; done) /
     
     elif [ "$choice" = "custom" ]; then
     
-      if [ -e "${exclude_selection:=ballup_exclude}" ]; then
+        if [ -e "${exclude_selection:=ballup_exclude}" ]; then
     
-         echo "Found exclude options in: $exclude_selection"
-         sleep 1
-    
-         tar "$comp_param" \
-             $(if [ -n "$verbose" ]; then echo "-v"; else echo "--totals"; fi) \
-             -cpf "$destination/$filename" \
-	     --exclude="$destination/$filename" \
-	     $(for entry in "${std_exclude_dirs[@]}"; do echo -n "--exclude=$entry "; done) --exclude-from=$exclude_selection /
+            echo "Found exclude options in: $exclude_selection"
+            sleep 1
+
+            tar "$comp_param" \
+                $(if [ -n "$verbose" ]; then echo "-v"; else echo "--totals"; fi) \
+                -Scpf "$destination/$filename" \
+                --exclude="$destination/$filename" \
+                $(for entry in "${std_exclude_dirs[@]}"; do echo -n "--exclude=$entry "; done) --exclude-from=$exclude_selection /
       
-      else       
-         echo "Neither the provided nor the default exclusion file could be found, aborting..."
-         exit -1
-      fi
+        else       
+            echo "Neither the provided nor the default exclusion file could be found, aborting..."
+            exit -1
+        fi
     else
-      echo "Either --full or --custom must be specified."
-      exit -1
+        echo "Either --full or --custom must be specified."
+        exit -1
     fi
     
     if [ $? = 0 ]; then   
@@ -126,58 +125,57 @@ EOF
 
 if [ $# -ne 0 ]; then
 
-   until [ $# -eq 0 ]
-   do
-      case $1 in
+    until [ $# -eq 0 ]
+    do
+        case $1 in
     
-        --help) help_me; exit 0;;
-                
-        --full) choice="full";;
-        
-        --custom) choice="custom"; 
-                  if [ -n "$2" ] && sed '/^-\+.*/{q2}' <<< "$2" > /dev/null; then 
-                     shift 
-                     exclude_selection=$(realpath -qe "$1")        
-                  fi
-                  ;;
-        
-        --path) shift; destination=$(realpath -qm "$1");;
-              
-        --algo) shift; compression=$1;;
+            --help) help_me; exit 0;;
+                    
+            --full) choice="full";;
 
-        --verbose) verbose="yes";;
-      
-        *) echo "That option is unsupported. Type --help for more info."; exit 0;;
+            --custom) choice="custom"; 
+                if [ -n "$2" ] && sed '/^-\+.*/{q2}' <<< "$2" > /dev/null; then 
+                    shift 
+                    exclude_selection=$(realpath -qe "$1")        
+                fi
+                ;;
+
+            --path) shift; destination=$(realpath -qm "$1");;
+                  
+            --algo) shift; compression=$1;;
+
+            --verbose) verbose="yes";;
+
+            *) echo "That option is unsupported. Type --help for more info."; exit 0;;
            
-       esac          
-       shift
-       
-   done
+        esac          
+        shift
+    done
  
-   if [ ! "$(id -u)" -eq 0 ];then
-      echo "Warning, you may lack sufficient privileges to access certain files!"
-   fi
+    if [ ! "$(id -u)" -eq 0 ];then
+        echo "Warning, you may lack sufficient privileges to access certain files!"
+    fi
 
-   echo "Initializing backup operation on local machine..."
+    echo "Initializing backup operation on local machine..."
 
-   while [ ! -d "${destination:=.}" ]
-   do
-      read -p "Bad path, specify a new one: " user_dest
-      destination=$(realpath -qm "$user_dest")
-   done
+    while [ ! -d "${destination:=.}" ]
+    do
+        read -p "Bad path, specify a new one: " user_dest
+        destination=$(realpath -qm "$user_dest")
+    done
 
-   snapshot_month=$(date +%B)
-   snapshot_year=$(date +%Y)
+    snapshot_month=$(date +%B)
+    snapshot_year=$(date +%Y)
 
-   filename="Backup-$snapshot_month-$snapshot_year.tar.${compression:=gzip}"
+    filename="Backup-$snapshot_month-$snapshot_year.tar.${compression:=gzip}"
 
-   if [ -e "$destination/$filename" ]; then
-      echo "Warning, there is already an archive of the same date, aborting..."
-      exit -1
-   fi  
+    if [ -e "$destination/$filename" ]; then
+        echo "Warning, there is already an archive of the same date, aborting..."
+        exit -1
+    fi  
 
-   echo "Creating archive in" $(realpath "$destination")
-   backup
+    echo "Creating archive in" $(realpath "$destination")
+    backup
           
 else
     echo "Insufficient amount of parameters. Type --help for a list of available options." 
